Imports

In [ ]:
import pandas as pd
import numpy as np
import math

small data try


In [ ]:
# x = np.array([
#     [1, 5],
# ])


# y = np.array([
#     [0, 1],
# ])


In [ ]:
x = np.array([
    [-1.0, 2.0],
    [0.5, -0.3],
    [2.1, 1.3],
    [-0.8, -1.5]
])


y = np.array([
    [0, 1],
    [1, 0],
    [1, 1],
    [0, 0]
])

In [ ]:
features = 2 #num of features
hidden_layer = 3 #hidden layer is number of features + 1
output_layer = 2 # number of calsses

bias_input = 1
bias_input_weight = 0.1
bias_hidden = 1
bias_hidden_weight = 0.2


In [ ]:
# weights_between_input_and_hidden = np.array([[0.1 ,0.2,0.3],
#  [0.4  ,0.5, 0.6]])
# weights_between_hidden_and_output = np.array([[0.3 ,0.3],
#  [0.4 ,0.4],
#  [0.5, 0.5]])


In [ ]:
weights_between_input_and_hidden = np.random.rand(features, hidden_layer) * 0.1
weights_between_hidden_and_output = np.random.rand(hidden_layer, output_layer) * 0.2

In [ ]:
# input_size = 2
# output_size = 2
# hidden_size = 4

# weights_between_input_and_hidden = np.random.uniform(size=(input_size, hidden_size))
# weights_between_hidden_and_output = np.random.uniform(size=(hidden_size, output_size))

activation functions

In [ ]:
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

def sigmoid(x):
    try:
        return 1 / (1 + np.exp(-x))
    except RuntimeWarning:
        return 0

def tanh(x):
    return 1 - np.tanh(x)**2

def leaky_relu(x, alpha = 0.01):
   return np.maximum(alpha * x, x)

def swish(x):
    return x * sigmoid(x)

a try outside before a big function

In [ ]:
step = 0.001
iterations = 5100
for i in range(iterations):
    # Forward
    hidden_layer_outputs = relu(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
    output_layer_outputs = relu(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)
    # if( i ==0 ):
    #   print(output_layer_outputs)
    #   print()

    # Backward
    grad_output = y - output_layer_outputs
    grad_weights_output = np.dot(hidden_layer_outputs.T, grad_output)
    grad_hidden = np.dot(grad_output, weights_between_hidden_and_output.T)
    grad_weights_hidden = np.dot(x.T, grad_hidden)


    # Update Weights and Biases
    weights_between_hidden_and_output += step * grad_weights_output
    bias_hidden_weight += step * bias_hidden_weight
    weights_between_input_and_hidden += step * grad_weights_hidden
    bias_input_weight += step * bias_input_weight


hidden_layer_outputs = relu(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
final_output = relu(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)

print("\nFinal Outputs:")
print(final_output)


Final Outputs:
[[0.         0.99677273]
 [0.63581868 0.01020523]
 [1.16364322 0.99291768]
 [0.20131693 0.        ]]


functions

In [ ]:
# ya rb this time yalaa try #40

#my training function
def NN_training_function(x, y, features, hidden_layer, output_layer,iterations,stop_number,step): #weights are generated randomly
  #set random data to begin with
  bias_input = 1
  bias_input_weight = 0.1
  bias_hidden = 2
  bias_hidden_weight = 0.2


  weights_between_input_and_hidden = np.random.rand(features, hidden_layer) * 0.1
  weights_between_hidden_and_output = np.random.rand(hidden_layer, output_layer) * 0.2

  #forward and backward process

  best_valid_output = None
  best_mse = np.inf

  for i in range(iterations):
    # forward
    hidden_layer_outputs = relu(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
    output_layer_outputs = relu(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)
    # if( i ==0 ):
    #   print(output_layer_outputs)
    #   print()

    # backward
    grad_output = y - output_layer_outputs
    grad_weights_output = np.dot(hidden_layer_outputs.T, grad_output)
    grad_hidden = np.dot(grad_output, weights_between_hidden_and_output.T)
    grad_weights_hidden = np.dot(x.T, grad_hidden)


    # update weights and biases
    weights_between_hidden_and_output += step * grad_weights_output
    bias_hidden_weight += step * bias_hidden_weight
    weights_between_input_and_hidden += step * grad_weights_hidden
    bias_input_weight += step * bias_input_weight





    error = y - output_layer_outputs
    mse = np.mean(np.square(error))

    if(mse<best_mse):
      best_mse = mse
      best_valid_output = output_layer_outputs
    # if(i% 100 == 0):
    print(f"the mean squard error in the {i} iteration is : ", mse * 100)
    diff = np.abs(error)

    if np.all(diff < stop_number):
        print(f"succefully trained :)")
        print(output_layer_outputs)
        return  best_valid_output,output_layer_outputs,bias_hidden_weight, bias_input_weight
    if np.isnan(output_layer_outputs).any():
      break



  hidden_layer_outputs = relu(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
  final_output = relu(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)
  print(f"With {iterations} iteration the output reached: ")
  print(final_output)
  print("The training reached: ", 100-mse*100, "% accuracy :)❤️")
  print("with best mse: ")
  print(best_valid_output)
  print("The best training reached: ", 100-best_mse*100, "% accuracy :)❤️")
  return best_valid_output,output_layer_outputs,bias_hidden_weight, bias_input_weight


In [ ]:
# ya rb this time yalaa try #40

#my training function
def NN_training_function_softmax(x, y, features, hidden_layer, output_layer,iterations,stop_number,step): #weights are generated randomly
  #set random data to begin with
  bias_input = 1
  bias_input_weight = 0.1
  bias_hidden = 2
  bias_hidden_weight = 0.3


  weights_between_input_and_hidden = np.random.rand(features, hidden_layer) * 0.1
  weights_between_hidden_and_output = np.random.rand(hidden_layer, output_layer) * 0.2

  #forward and backward process

  best_valid_output = None
  best_mse = np.inf

  for i in range(iterations):
    # forward
    hidden_layer_outputs = softmax(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
    output_layer_outputs = softmax(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)
    # if( i ==0 ):
    #   print(output_layer_outputs)
    #   print()

    # backward
    grad_output = y - output_layer_outputs
    grad_weights_output = np.dot(hidden_layer_outputs.T, grad_output)
    grad_hidden = np.dot(grad_output, weights_between_hidden_and_output.T)
    grad_weights_hidden = np.dot(x.T, grad_hidden)


    # update weights and biases
    weights_between_hidden_and_output += step * grad_weights_output
    bias_hidden_weight += step * bias_hidden_weight
    weights_between_input_and_hidden += step * grad_weights_hidden
    bias_input_weight += step * bias_input_weight





    error = y - output_layer_outputs
    mse = np.mean(np.square(error))

    if(mse<best_mse):
      best_mse = mse
      best_valid_output = output_layer_outputs
      if np.isnan(weights_between_hidden_and_output).sum() <= 100 and np.isnan(weights_between_input_and_hidden).sum() <= 100:
        best_weight_h = weights_between_input_and_hidden
        best_weight_o = weights_between_hidden_and_output
        best_bias_input = bias_input_weight
        best_bias_hidden = bias_hidden_weight


    # if(i% 100 == 0):
    print(f"the mean squard error in the {i} iteration is : ", mse * 100)
    diff = np.abs(error)

    if np.all(diff < stop_number):
        print(f"succefully trained :)")
        print(output_layer_outputs)
        return best_valid_output,output_layer_outputs,best_bias_hidden, best_bias_input,best_weight_h, best_weight_o
    if np.isnan(output_layer_outputs).any():
      break



  hidden_layer_outputs = relu(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
  final_output = relu(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)
  print(f"With {iterations} iteration the output reached: ")
  print(final_output)
  print("The training reached: ", 100-mse*100, "% accuracy :)❤️")
  print("with best mse: ")
  print(best_valid_output)
  print("The best training reached: ", 100-best_mse*100, "% accuracy :)❤️")
  return best_valid_output,output_layer_outputs,best_bias_hidden, best_bias_input,best_weight_h, best_weight_o


In [ ]:
############3same but clip for nan problem
import numpy as np

def clip_gradients(grad, threshold):
    clipped_grad = np.clip(grad, -threshold, threshold)
    return clipped_grad

def NN_training_function_softmax_clip(x, y, features, hidden_layer, output_layer, iterations, stop_number, step, gradient_clip_threshold=1.0):
    # set random data to begin with
    bias_input = 1
    bias_input_weight = 0.1
    bias_hidden = 2
    bias_hidden_weight = 0.3

    #set weights random
    weights_between_input_and_hidden = np.random.rand(features, hidden_layer) * 0.1
    weights_between_hidden_and_output = np.random.rand(hidden_layer, output_layer) * 0.2

    #stuff i will return
    best_weights_input_hidden = None
    best_weights_hidden_output = None
    best_bias_input_weight = bias_input_weight
    best_bias_hidden_weight = bias_hidden_weight
    best_mse = np.inf

    for i in range(iterations):
        # forward
        hidden_layer_outputs = softmax(np.dot(x, weights_between_input_and_hidden) + bias_input_weight)
        output_layer_outputs = softmax(np.dot(hidden_layer_outputs, weights_between_hidden_and_output) + bias_hidden_weight)

        # backward
        alpha_output = y - output_layer_outputs
        alpha_weights_output = np.dot(hidden_layer_outputs.T, alpha_output)
        alpha_hidden = np.dot(alpha_output, weights_between_hidden_and_output.T)
        alpha_weights_hidden = np.dot(x.T, alpha_hidden)

        # the clipping proccess to prevent nan try 20
        alpha_weights_output = clip_gradients(alpha_weights_output, gradient_clip_threshold)
        alpha_weights_hidden = clip_gradients(alpha_weights_hidden, gradient_clip_threshold)

        # update
        weights_between_hidden_and_output += step * alpha_weights_output
        bias_hidden_weight += step * bias_hidden_weight
        weights_between_input_and_hidden += step * alpha_weights_hidden
        bias_input_weight += step * bias_input_weight

        # mse calculations
        error = y - output_layer_outputs
        mse = np.mean(np.square(error))

        # update best weights and biases to return baest results
        if mse < best_mse:
            best_mse = mse
            best_weights_input_hidden = np.copy(weights_between_input_and_hidden)
            best_weights_hidden_output = np.copy(weights_between_hidden_and_output)
            best_bias_input_weight = bias_input_weight
            best_bias_hidden_weight = bias_hidden_weight


        print(f"The mean squared error in iteration {i} is: {mse * 100}")


        diff = np.abs(error)
        if np.all(diff < stop_number):
            print("Successfully trained :)")
            return best_bias_hidden_weight, best_bias_input_weight, best_weights_input_hidden , best_weights_hidden_output


        if np.isnan(output_layer_outputs).any():
            break

    print(f"With {iterations} iterations, the output reached:")
    print(output_layer_outputs)
    print("Training accuracy:", 100 - mse * 100, "%")
    print("Best MSE:", best_mse*100)
    return best_bias_hidden_weight, best_bias_input_weight, best_weights_input_hidden , best_weights_hidden_output


testing on train with diffrent steps and iterations


In [ ]:
stop_number = 0.1
iterations = 5000
step = 0.01
#relu acti_function
NN_training_function(x, y, features, hidden_layer, output_layer,iterations,stop_number,step)

the mean squard error in the 0 iteration is :  28.814491337261273
the mean squard error in the 1 iteration is :  28.363770739316095
the mean squard error in the 2 iteration is :  27.905498204559702
the mean squard error in the 3 iteration is :  27.44002332172128
the mean squard error in the 4 iteration is :  26.967806721310584
the mean squard error in the 5 iteration is :  26.489422428664266
the mean squard error in the 6 iteration is :  26.005559093484376
the mean squard error in the 7 iteration is :  25.51701987722676
the mean squard error in the 8 iteration is :  25.02472079014592
the mean squard error in the 9 iteration is :  24.52968728913716
the mean squard error in the 10 iteration is :  24.033048976594113
the mean squard error in the 11 iteration is :  23.538161605172142
the mean squard error in the 12 iteration is :  23.046633148963302
the mean squard error in the 13 iteration is :  22.557749454298524
the mean squard error in the 14 iteration is :  22.072960448734573
the mean 

(array([[0.        , 0.99695414],
        [0.63596434, 0.00473038],
        [1.16136836, 0.9978781 ],
        [0.20498781, 0.        ]]),
 array([[nan, nan],
        [nan, nan],
        [nan, nan],
        [nan, nan]]),
 279.8917576683846,
 139.9458788341923)

try with bigger data

In [ ]:
from keras.datasets import mnist

In [ ]:
(train_x, train_y), (test_x, test_y) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
train_x

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [ ]:
train_x.shape

(60000, 28, 28)

In [ ]:
# list_ = []
# for i in range(len(train_y)):
#   if(train_y[i] not in list_):
#     list_.append(train_y[i])
# print(list_)
# y_train = np.eye(len(list_))[list_.sort()]


unique_classes = np.unique(train_y)

y_train = np.zeros((len(train_y), len(unique_classes)))

for i, val in enumerate(train_y):
    index = np.where(unique_classes == val)[0][0]
    y_train[i, index] = 1
y_train = y_train[:, :-1]

y_train.shape

(60000, 9)

In [ ]:
x_train_flat = train_x.reshape(-1, 28*28)
x_train = x_train_flat.astype("float32") / 255.0

x_train.shape

(60000, 784)

In [ ]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
import random

features = 784
hidden_layer = 785
output_layer = 9

# bias_input = 1
# bias_input_weight = random.random()
# bias_hidden = 1
# bias_hidden_weight = random.random()

weights_between_input_and_hidden = np.random.rand(features, hidden_layer) * bias_input_weight
weights_between_hidden_and_output = np.random.rand(hidden_layer, output_layer) * bias_hidden_weight

In [ ]:
stop_number = 0.01
iterations = 10000
# step = 1e-6
step = 0.0001
#bias  = 0.1 for both

x_, x_2, bias_input_updated0, bias_hidden_updated0, w_h0,w_o0= NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019673492876382
the mean squard error in the 1 iteration is :  8.972218634018967
the mean squard error in the 2 iteration is :  8.933478022298125
the mean squard error in the 3 iteration is :  8.89612609100966
the mean squard error in the 4 iteration is :  8.838694400181206
the mean squard error in the 5 iteration is :  8.718339638721131
the mean squard error in the 6 iteration is :  8.52088450073884
the mean squard error in the 7 iteration is :  8.233428353211034
the mean squard error in the 8 iteration is :  7.7923423637300635
the mean squard error in the 9 iteration is :  7.201135775280078
the mean squard error in the 10 iteration is :  6.550522309841571
the mean squard error in the 11 iteration is :  5.953150542459261
the mean squard error in the 12 iteration is :  5.490101272177579
the mean squard error in the 13 iteration is :  5.1690512926541095
the mean squard error in the 14 iteration is :  4.950901982980691
the mean squard erro

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 42 iteration is :  nan
With 10000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.05173032 0.03430668 0.02687676 ... 0.03845231 0.02924163 0.14482228]
 [0.86496734 0.01292909 0.02769961 ... 0.01752674 0.01536173 0.01469976]
 [0.04569197 0.04515406 0.05517142 ... 0.05030005 0.06105857 0.05115786]
 ...
 [0.05173032 0.03430668 0.02687676 ... 0.03845231 0.02924163 0.14482228]
 [0.01862493 0.01488862 0.01955063 ... 0.86485193 0.01439245 0.0160836 ]
 [0.04089108 0.08488113 0.07972007 ... 0.05780971 0.05911555 0.50520761]]
The best training reached:  95.6955586449936 % accuracy :)❤️


In [ ]:
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.00001
#bias 0.05 for both
x_, x_2, bias_input_updated, bias_hidden_updated, w_h,w_o= NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019861932148658
the mean squard error in the 1 iteration is :  9.014912894897723
the mean squard error in the 2 iteration is :  9.00999346937593
the mean squard error in the 3 iteration is :  9.005123734545394
the mean squard error in the 4 iteration is :  9.000321059946991
the mean squard error in the 5 iteration is :  8.99559932004339
the mean squard error in the 6 iteration is :  8.990968514269843
the mean squard error in the 7 iteration is :  8.986434754334814
the mean squard error in the 8 iteration is :  8.982000523895225
the mean squard error in the 9 iteration is :  8.977665098000582
the mean squard error in the 10 iteration is :  8.973425020835705
the mean squard error in the 11 iteration is :  8.969274565292471
the mean squard error in the 12 iteration is :  8.965206124619893
the mean squard error in the 13 iteration is :  8.96121050827
the mean squard error in the 14 iteration is :  8.957277129211363
the mean squard error in t

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 351 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.01980191 0.02292711 0.02389102 ... 0.01712861 0.01877807 0.2616669 ]
 [0.84526085 0.01242715 0.01474543 ... 0.0145765  0.01463868 0.01352075]
 [0.02924315 0.02094228 0.03229354 ... 0.16584497 0.02387521 0.02179571]
 ...
 [0.01980191 0.02292711 0.02389102 ... 0.01712861 0.01877807 0.2616669 ]
 [0.04165776 0.04094805 0.04030821 ... 0.55431523 0.02801269 0.11687096]
 [0.04166065 0.04095345 0.04031151 ... 0.554212   0.02801522 0.11692313]]
The best training reached:  94.95477702167483 % accuracy :)❤️


In [ ]:
#try 180 :(
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.0001
#0.3 for both bias
x_, x_2, bias_input_updated1, bias_hidden_updated1,w_h1,w_o1  = NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019448631841877
the mean squard error in the 1 iteration is :  8.970717364176394
the mean squard error in the 2 iteration is :  8.9263123777589
the mean squard error in the 3 iteration is :  8.875501809281037
the mean squard error in the 4 iteration is :  8.784918498565343
the mean squard error in the 5 iteration is :  8.598393519942697
the mean squard error in the 6 iteration is :  8.258597384336964
the mean squard error in the 7 iteration is :  7.764716663909314
the mean squard error in the 8 iteration is :  7.178194079601822
the mean squard error in the 9 iteration is :  6.583452653631
the mean squard error in the 10 iteration is :  6.069373697231734
the mean squard error in the 11 iteration is :  5.659265592151018
the mean squard error in the 12 iteration is :  5.343778181479762
the mean squard error in the 13 iteration is :  5.102355590956115
the mean squard error in the 14 iteration is :  4.910858119552007
the mean squard error in 

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 38 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.02053349 0.02511531 0.02345612 ... 0.02172905 0.01857014 0.11737302]
 [0.8113189  0.01336944 0.01542331 ... 0.01556709 0.01801949 0.01846005]
 [0.04980092 0.04921066 0.05627321 ... 0.05210931 0.09479688 0.05980794]
 ...
 [0.02053349 0.02511531 0.02345612 ... 0.02172905 0.01857014 0.11737302]
 [0.0219118  0.01484731 0.0176828  ... 0.85580402 0.0148219  0.01505776]
 [0.05231382 0.072032   0.10295396 ... 0.05044853 0.0465346  0.50342457]]
The best training reached:  95.9247433587724 % accuracy :)❤️


In [ ]:
#try 180 :(
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.0001
#0.2 for one 0.3 for other
x_, x_2, bias_input_updated2, bias_hidden_updated2,w_h2,w_o2  = NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019705842034192
the mean squard error in the 1 iteration is :  8.97293193194637
the mean squard error in the 2 iteration is :  8.935549697428778
the mean squard error in the 3 iteration is :  8.900125599251512
the mean squard error in the 4 iteration is :  8.851340299332733
the mean squard error in the 5 iteration is :  8.757510488800415
the mean squard error in the 6 iteration is :  8.558045646107455
the mean squard error in the 7 iteration is :  8.199747875756604
the mean squard error in the 8 iteration is :  7.71605155034499
the mean squard error in the 9 iteration is :  7.178436527822369
the mean squard error in the 10 iteration is :  6.651087833704625
the mean squard error in the 11 iteration is :  6.191037350966868
the mean squard error in the 12 iteration is :  5.796052239262319
the mean squard error in the 13 iteration is :  5.4381689932957125
the mean squard error in the 14 iteration is :  5.113345462702294
the mean squard error

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 46 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.03608704 0.02176879 0.02116124 ... 0.0240807  0.02583018 0.02733917]
 [0.84645546 0.01239241 0.0384963  ... 0.02194213 0.01559285 0.01469569]
 [0.03965905 0.0368383  0.03996678 ... 0.0365893  0.04521622 0.03960214]
 ...
 [0.03608659 0.02176842 0.02116083 ... 0.02408033 0.02582977 0.02733872]
 [0.01282895 0.0124953  0.03783808 ... 0.85508122 0.01269313 0.01358407]
 [0.04087381 0.08383835 0.05001269 ... 0.04861685 0.04860219 0.49427219]]
The best training reached:  96.71020023864361 % accuracy :)❤️


In [ ]:
#try 190 :(
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.0001
#0.2  for both
x_, x_2, bias_input_updated3, bias_hidden_updated3,w_h3,w_o3  = NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019941651099291
the mean squard error in the 1 iteration is :  8.971875864004282
the mean squard error in the 2 iteration is :  8.929753745245064
the mean squard error in the 3 iteration is :  8.875350613582214
the mean squard error in the 4 iteration is :  8.756292548343918
the mean squard error in the 5 iteration is :  8.568781081606748
the mean squard error in the 6 iteration is :  8.299165763138836
the mean squard error in the 7 iteration is :  7.94151024143612
the mean squard error in the 8 iteration is :  7.531878396645503
the mean squard error in the 9 iteration is :  7.0952800092653865
the mean squard error in the 10 iteration is :  6.623008886658341
the mean squard error in the 11 iteration is :  6.171752011817653
the mean squard error in the 12 iteration is :  5.827540387190212
the mean squard error in the 13 iteration is :  5.564384360047266
the mean squard error in the 14 iteration is :  5.359602728461152
the mean squard erro

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 37 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.02416443 0.0239676  0.03120095 ... 0.02370847 0.01966715 0.08081713]
 [0.85031395 0.01268651 0.0168804  ... 0.01916226 0.01554064 0.01468636]
 [0.04737717 0.04621828 0.05162538 ... 0.04752429 0.05821954 0.08637903]
 ...
 [0.02416443 0.0239676  0.03120095 ... 0.02370847 0.01966715 0.08081713]
 [0.01676689 0.01499047 0.1398144  ... 0.73685218 0.01506768 0.01649383]
 [0.03253352 0.05588029 0.36034177 ... 0.03450579 0.04277385 0.35251555]]
The best training reached:  95.33260302313468 % accuracy :)❤️


In [ ]:
#try 190 :(
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.0001
#0.2  0.4 bias
x_, x_2, bias_input_updated4, bias_hidden_updated4,w_h4,w_o4  = NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019625805341516
the mean squard error in the 1 iteration is :  8.97173105204239
the mean squard error in the 2 iteration is :  8.933515730543967
the mean squard error in the 3 iteration is :  8.897713060098011
the mean squard error in the 4 iteration is :  8.848252428983423
the mean squard error in the 5 iteration is :  8.753370013036168
the mean squard error in the 6 iteration is :  8.556224306402965
the mean squard error in the 7 iteration is :  8.224789045687231
the mean squard error in the 8 iteration is :  7.794759442486676
the mean squard error in the 9 iteration is :  7.316686582018756
the mean squard error in the 10 iteration is :  6.850509228298425
the mean squard error in the 11 iteration is :  6.425871680034121
the mean squard error in the 12 iteration is :  6.054269228644913
the mean squard error in the 13 iteration is :  5.744427199719459
the mean squard error in the 14 iteration is :  5.48167232618516
the mean squard error 

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 39 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.03153974 0.01818274 0.0199957  ... 0.02094559 0.01911334 0.03941105]
 [0.87257005 0.01250559 0.01508622 ... 0.01904016 0.01806081 0.01431146]
 [0.0418835  0.04795439 0.04722313 ... 0.04504189 0.05283501 0.28575166]
 ...
 [0.03153974 0.01818274 0.0199957  ... 0.02094559 0.01911334 0.03941105]
 [0.01373211 0.01243618 0.0168121  ... 0.86025342 0.01270665 0.01528477]
 [0.0418835  0.04795439 0.04722313 ... 0.04504189 0.05283501 0.28575166]]
The best training reached:  95.61844475737668 % accuracy :)❤️


In [ ]:
#try 190 :(
stop_number = 0.01
iterations = 3000
# step = 1e-6
step = 0.0001
#0.2  0.1 bias
x_, x_2, bias_input_updated5, bias_hidden_updated5,w_h5,w_o5 = NN_training_function_softmax(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


the mean squard error in the 0 iteration is :  9.019509209502964
the mean squard error in the 1 iteration is :  8.97191881901144
the mean squard error in the 2 iteration is :  8.931091519683262
the mean squard error in the 3 iteration is :  8.88914928981077
the mean squard error in the 4 iteration is :  8.82498549846663
the mean squard error in the 5 iteration is :  8.7078635276005
the mean squard error in the 6 iteration is :  8.519457891774207
the mean squard error in the 7 iteration is :  8.245490958343012
the mean squard error in the 8 iteration is :  7.855235986357857
the mean squard error in the 9 iteration is :  7.361991279158701
the mean squard error in the 10 iteration is :  6.8523805754480085
the mean squard error in the 11 iteration is :  6.400929059158599
the mean squard error in the 12 iteration is :  6.020546253376953
the mean squard error in the 13 iteration is :  5.69266577835722
the mean squard error in the 14 iteration is :  5.422218605042894
the mean squard error in 

<ipython-input-43-82100862f3e6>:5: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
<ipython-input-43-82100862f3e6>:6: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x, axis=1, keepdims=True)


the mean squard error in the 38 iteration is :  nan
With 3000 iteration the output reached: 
[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
The training reached:  nan % accuracy :)❤️
with best mse: 
[[0.0407877  0.05797076 0.04505346 ... 0.03547415 0.06409105 0.30543701]
 [0.78253301 0.01659529 0.02632117 ... 0.04278957 0.02850886 0.01852023]
 [0.03377853 0.03147608 0.03708911 ... 0.03209552 0.03453796 0.03278394]
 ...
 [0.0407877  0.05797076 0.04505346 ... 0.03547415 0.06409105 0.30543703]
 [0.78253301 0.01659529 0.02632117 ... 0.04278957 0.02850886 0.01852023]
 [0.0407877  0.05797076 0.04505346 ... 0.03547415 0.06409105 0.30543703]]
The best training reached:  95.37265058565872 % accuracy :)❤️


In [ ]:
#0.1 0.3 bias
stop_number = 0.01
iterations = 260

step = 0.01

bias_input_updated6, bias_hidden_updated6,w_h6,w_o6 = NN_training_function_softmax_clip(x_train, y_train, features, hidden_layer, output_layer,iterations,stop_number,step)


The mean squared error in iteration 0 is: 9.019644826466266
The mean squared error in iteration 1 is: 9.00279468423223
The mean squared error in iteration 2 is: 8.981064370420505
The mean squared error in iteration 3 is: 8.953874750574158
The mean squared error in iteration 4 is: 8.922873564564743
The mean squared error in iteration 5 is: 8.889298540528142
The mean squared error in iteration 6 is: 8.854004828889767
The mean squared error in iteration 7 is: 8.817521737196197
The mean squared error in iteration 8 is: 8.780107388532347
The mean squared error in iteration 9 is: 8.742226526122728
The mean squared error in iteration 10 is: 8.704107312368938
The mean squared error in iteration 11 is: 8.665837306050129
The mean squared error in iteration 12 is: 8.627561631938963
The mean squared error in iteration 13 is: 8.589449310222342
The mean squared error in iteration 14 is: 8.551389328806986
The mean squared error in iteration 15 is: 8.51328891529557
The mean squared error in iteration 

In [ ]:
#test
x_test_flat = test_x.reshape(-1, 28*28)
x_test = x_test_flat.astype("float32") / 255.0

unique_classes = np.unique(test_y)

y_test = np.zeros((len(test_y), len(unique_classes)))

for i, val in enumerate(test_y):
    index = np.where(unique_classes == val)[0][0]
    y_test[i, index] = 1
y_test = y_test[:, :-1]

x_test.shape

(10000, 784)

test data

In [ ]:
def predict(test_x):
    h = softmax(np.dot(test_x, w_h6) + bias_input_updated6)
    final_output = softmax(np.dot(h, w_o6) + bias_hidden_updated6)
    return final_output

predictions = predict(x_test)
error = y_test - predictions

mse = np.mean(np.square(error))

print("The test reached: ", 100-mse*100, "% accuracy :)💛")


The test reached:  96.81683679458018 % accuracy :)💛


In [ ]:
predictions

array([[0.01048762, 0.00958367, 0.00972168, ..., 0.00989813, 0.92034227,
        0.01044277],
       [0.01180662, 0.00706907, 0.16958688, ..., 0.00786594, 0.0077623 ,
        0.05686566],
       [0.01097143, 0.89159076, 0.01661695, ..., 0.01288068, 0.01035634,
        0.02157476],
       ...,
       [0.08792149, 0.08674019, 0.08722037, ..., 0.08925029, 0.15530304,
        0.09878374],
       [0.02825579, 0.03239367, 0.03498219, ..., 0.02703205, 0.02681175,
        0.62446936],
       [0.01273505, 0.00933288, 0.01561029, ..., 0.87016348, 0.00954007,
        0.01257391]])

In [ ]:
y_test

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])